hyperparameters:
  alphas:
  - 0.0001
  - 0.001
  - 0.01
  - 0.1
  - 1.0
  - 10.0
  - 100.0
  c_values:
  - 0.0001
  - 0.001
  - 0.01
  - 0.1
  - 1.0
  - 10.0
  - 100.0
  elastic_net_params:
    l1_ratio: 0.5
    max_iter: 2000
    tol: 0.01
  lasso_params:
    max_iter: 2000
    tol: 0.01
  ridge_params:
    max_iter: 2000
    tol: 0.0001

random_state: 42
cv_folds: 5